name: Simple
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  native:
    name: "Simple: GHC ${{ matrix.ghc }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        ghc: ['8.10','9.0','9.2','9.4']
      fail-fast: false
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Set up Haskell
        id: setup-haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: '3.10.1.0'

      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Build
        run: cabal build all --enable-tests

      - name: Test
        run: cabal test all --enable-tests --test-show-details=direct
  wasi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.6', '9.8', '9.10', '9.12']
      fail-fast: false
    steps:
    - name: setup-ghc-wasm32-wasi
      run: |
        cd $(mktemp -d)
        curl -L https://gitlab.haskell.org/haskell-wasm/ghc-wasm-meta/-/archive/$GHC_WASM_META_REV/ghc-wasm-meta.tar.gz | tar xz --strip-components=1
        ./setup.sh
        ~/.ghc-wasm/add_to_github_path.sh
      env:
        GHC_WASM_META_REV: f0faac335c6f5e967d1bdbfca5768232483fd2a8
        FLAVOUR: ${{ matrix.ghc }}
    - uses: actions/checkout@v4
    - name: Build
      run: |
        wasm32-wasi-cabal build splitmix splitmix:test:examples splitmix:test:initialization
    - name: Test
      run: |
        for test in examples initialization; do
          echo --- Running test $test ---
          wasmtime $(wasm32-wasi-cabal list-bin splitmix:test:$test)
        done
